
# SConstruct

import os

cxxFlags = ['-std=c++14']

ros2_ws_path = '/home/alsora/workspaces/ros2_sdk'

print '************ --- ************'
print 'ROS2 SDK Path:', ros2_ws_path
print '************ --- ************'

dependencies = [
    'rclcpp',
    'rcl',
    'rcl_interfaces',
    'rcutils',
    'rosidl_typesupport_interface',
    'rosidl_generator_c',
    'rmw',
    'rmw_implementation',
    'builtin_interfaces',
    'rosidl_typesupport_cpp',
    'rosidl_generator_cpp',
    'std_msgs',
]


target_libs = [
    'rclcpp',
    'rcutils',
    'rcl',
    'builtin_interfaces__rosidl_typesupport_cpp',
    'rosidl_typesupport_cpp',
    'std_msgs__rosidl_typesupport_cpp',
]


ros2_sdk_path = os.path.join(ros2_ws_path, 'install')
include_dirs =[os.path.join(ros2_sdk_path, dep_path, 'include') for dep_path in dependencies]
lib_dirs =[os.path.join(os.path.join(ros2_sdk_path, dep_path), 'lib') for dep_path in dependencies]


#print include_dirs
#print lib_dirs

env = Environment()
env.Append(CXXFLAGS = cxxFlags)
env.Append(CPPPATH = include_dirs)
env.Append(LIBPATH= lib_dirs)
env.Append(LIBS= target_libs)
env.Program("hello_ros", ["hello_ros.cpp"])


conf = Configure(env)
for lib_base_name in target_libs:
    conf.CheckLib(lib_base_name)
env = conf.Finish()



